name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src:$PYTHONPATH" >> $GITHUB_ENV

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipx and tools
        run: |
          python -m pip install -U pipx
          pipx install ruff pytest behave coverage
          pipx inject pytest pytest-xdist pytest-cov

      - name: Install project requirements
        run: pip install -r requirements.txt

      - name: Run pytest with coverage
        run: |
          coverage run -m pytest -n auto

      - name: Run behave with coverage
        run: |
          coverage run -a -m behave

      - name: Combine coverage reports
        run: |
          coverage combine
          coverage report
          coverage xml

      - name: Check minimum coverage (60%)
        run: |
          percent=$(coverage report | grep TOTAL | awk '{print $NF}' | sed 's/%//')
          echo "Total Coverage: $percent%"
          if [ "$(printf '%.0f' "$percent")" -lt 60 ]; then
            echo "Insufficient coverage (<60%)"
            exit 1
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: coverage.xml