name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: python -m pip install -U pipx
      - run: pipx install ruff pytest behave coverage
      - run: pipx inject pytest pytest-xdist pytest-cov
      # - run: pip install -r requirements.txt
      # - run: ruff src tests --quiet
      # - run: pytest -n auto --cov=guardian
      # - run: behave -f progress